export const extentionFill = {
  txt: "simple text",
  js: "console.log('hello world')",
  cjs: "console.log('hello world')",
  ts: "console.log('hello world')",
  html: "<p>hello world</p>",
  css: "p{color:red}",
  scss: "p{color:red}",
  sass: "p{color:red}",
  less: "p{color:red}",
  json: '{"name":"zs"}',
  md: "# hello world!",
  yml: "name: zs",
  yaml: "name: zs",
  xml: "<xml></xml>",
  java: "public static void main(String[] args){}",
  py: "print('hello world')",
  php: "<?php echo 'hello world';",
  hbs: "<p>hello world</p>",
  handlebars: "<p>hello world</p>",
  vue: "<template><p>hello world</p></template>",
  svelte: "<scritpt>console.log('hello world')</script>",
  elm: "main = () -> ()",
  rs: 'fn main() {\n    println!("hello world");\n}',
  rsx: "import React from 'react';\nimport ReactDOM from 'react-dom';\n\nconst App = () => {\n    return <div>hello world</div>\n};\n\nReactDom.render(<App />, document.getElementById('root'));",
};
